### ISSUE TITLE
support different size projects

### ISSUE THREAD

**Issue by mattvenn** [mattvenn/multi_project_tools#8]

**Comment by mattvenn** [comment]
turn off wishbone and save pins, then can have smaller dies

stack up the projects to make a best fit?

**Comment by zbigos** [comment]
Since most of this code is written in python, I think I could start working on this?

I just wanted to ask if by "support different size projects" you mean supporting arbitrary sizes in um^2, passed in projects.yaml, or would a solution where multiple blocks are joined to be above the minimum area would be enough.

<img src="https://user-images.githubusercontent.com/26178072/133399519-08249dae-fff9-46d5-88f7-f35ad35fc3bd.png" width="250" height="250">

Also, this might not be such a great suggestion, but wouldn't it make sense to have this tool generate layout for the bus that connects those cells together? It seems that there is a lot of space wasted between them.  

In any case, if you think that I should start working on either of these, I'd be more than happy to provide a design doc and start development on it

**Comment by mattvenn** [comment]
Hey, thanks for the offer of helping! 
The number of pins a macro has determines the minimum size. I also want some standardisation, so we are thinking of some options: wishbone, logic analyser, memory interface, gpio. Then you toggle them on or off and get different minimum sizes.

Re the bus, initially I thought the same, but was talked out of it by the openlane devs. You're right there is a lot of wasted space and I feel we can improve on this.

Why don't you join the next work session with me and Paweł. Check the mpw-preparation channel on the discord.
